version: '3'
services:
  hyperf:
    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
    volumes:
      - ./wwwroot:/wwwroot
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=dev
    tty: true
    networks:
      - compose
  mysql:
    image: mysql:latest
    volumes:
      - ./config/mysql/conf.d/:/etc/mysql/conf.d/
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=dev
    networks:
      - compose
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - compose
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - compose
networks:
  compose: